sudo: required

language: python

services:
  - docker

install: true

before_script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t univizor/u3 .

script:
  - docker run -ti --rm --name u3 -e U3_ENV=test --entrypoint python univizor/u3 -m unittest discover

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push univizor/u3:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "production" ]; then
    docker push univizor/u3:production;
    fi
