version: '2'
services:
  pg:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=u3_dev

  u3:
    build: .
    image: univizor/u3:latest
    environment:
      - DATABASE_URL=postgresql://postgres:@pg:5432/u3_dev
    links:
      - pg
    depends_on:
      - create_tables
    volumes:
      - .:/home/u3
    command: "bf -a categories=biologija"

  create_tables:
    build: .
    image: univizor/u3:latest
    environment:
      - DATABASE_URL=postgresql://postgres:@pg:5432/u3_dev
    links:
      - pg
    entrypoint: python
    depends_on:
      - pg
    restart: on-failure:3
    command: recreate_database.py
    volumes:
      - .:/home/u3